CREATE TABLE DIM_FUND (
    FUND_ID INTEGER PRIMARY KEY,
    AMFI_CODE INTEGER UNIQUE,
    SCHEME_NAME TEXT,
    FUND_HOUSE TEXT,
    CATEGORY TEXT
);

CREATE TABLE DIM_DATE (
    DATE_ID INTEGER PRIMARY KEY,
    FULL_DATE DATE,
    YEAR INTEGER,
    MONTH INTEGER,
    DAY INTEGER
);

CREATE TABLE FACT_NAV (
    NAV_ID INTEGER PRIMARY KEY,
    AMFI_CODE INTEGER,
    DATE_ID INTEGER,
    NAV REAL
);

CREATE TABLE FACT_TRANSACTIONS (
    TRANSACTION_ID INTEGER PRIMARY KEY,
    INVESTOR_ID INTEGER,
    AMFI_CODE INTEGER,
    DATE_ID INTEGER,
    AMOUNT_INR REAL,
    TRANSACTION_TYPE TEXT
);

CREATE TABLE FACT_PERFORMANCE (
    PERFORMANCE_ID INTEGER PRIMARY KEY,
    AMFI_CODE INTEGER,
    RETURN_1YR_PCT REAL,
    RETURN_3YR_PCT REAL,
    RETURN_5YR_PCT REAL,
    EXPENSIVE_RATIO_PCT REAL
);

CREATE TABLE FACT_AUM (
    AUM_ID INTEGER PRIMARY KEY,
    AMFI_CODE INTEGER,
    AUM_CRORE REAL
);

